### ISSUE TITLE
pyyaml  inconsistent version in Pip lock files and security warning

### ISSUE THREAD

**Issue by cicorias** [Microsoft/agogosml#232]
The version of pyyaml referenced differently in 
```
./agogosml/Pipfile
./agogosml/Pipfile.lock  
./agogosml/setup.py
./agogosml_cli/Pipfile.lock
```
Additionally, security scan recommends update to `4.2b1` - lockfiles!
```
[packages]

pyyaml = ">=4.2b1"
```

### Issue Template

- [x] Does your issue follow our [Code of Conduct](https://opensource.microsoft.com/codeofconduct/)?

- [x] Ensure you are up-to-date with master.

- [x] Search existing issues.

- [x] Part of the project with issues: (ie. Agogosml, Deployment, CLI)

- [x] Indicate OS, version of Python (Note: Only Python 3.7 is currently supported.)
    - [x] Include versions of tooling where appropriate (Terraform, Kubernetes, Docker, etc.)

**Comment by sayar** [comment]
This isn't an issue. Pipfile.lock includes both dev and non-dev dependencies. Pipfiles also collapse the dependency tree. The below files all reference a version greater than `pyyaml = ">=4.2b1"`:
```
./agogosml/Pipfile
./agogosml/Pipfile.lock  
./agogosml/setup.py
```

The security warning is triggered only for the ./agogosml_cli/Pipfile.lock file. There is a dev dependency in the agogosml_cli Pipfile that includes an old version of pyyaml hence why the security warning appears. When you do pip install agogosml_cli, you aren't pulling down pyyaml. You can verify yourself by deleting all the dev dependencies and regenerating the Pipfile.lock (no pyyaml). Happy to push a Pipfile.lock for agogosml_cli that doesn't include the dev dependencies to make the security warning go away but that requires me to remove the offending dev dependency from the Pipfile and include manual instructions to install. IMO it's not worth it.

P.S. @cicorias only repository admins can see GitHub security warnings. Please email directly about security warnings instead of posting as an issue.

**Comment by c-w** [comment]
Just as a note: the pyyaml dependency is pulled in as a transitive dependency of [watchdog](https://github.com/Microsoft/agogosml/blob/1b13ef7fdd34a73991a6033564a3eb9573efef73/agogosml_cli/Pipfile#L8) which is used for [make servedocs](https://github.com/Microsoft/agogosml/blob/1b13ef7fdd34a73991a6033564a3eb9573efef73/agogosml_cli/Makefile#L80-L81).

**Comment by c-w** [comment]
Note that the root cause of this was resolved in https://github.com/Microsoft/agogosml/pull/229 since pipenv was replaced with pip.
